### ISSUE TITLE
trim `language_info.version`

### ISSUE THREAD

**Issue by mgab** [toobaz/ipynb_output_filter#12]
Sorry for multi-posting, but I thought it was better to keep things in different issues.

The problem I'm trying to solve appears if working with computers that have different (but compatible) versions of the programming language (say python `2.7.11` in computer A and `2.7.9` in computer B). Then, just by running a notebook with a computer different from the one to run and commit the file, git/mercurial will detect uncommitted changes.

I'm thinking on processing the `metadata.language_info.version` to keep only major and minor version number, and discard the patch version number (http://semver.org/), so that `2.7.11` would become `2.7`. It sounds weird, but in principle patch version should not affect backwards compatibility, so it should be safe. Still, I'm not sure it is a good thing for the general use case. What do you think?

Shall I pull-request or keep it as a personal hack?

**Comment by toobaz** [comment]
The idea makes a lot of sense. Do you think it would be a problem if we just dropped the `metadata.language_info.version` field?!

**Comment by mgab** [comment]
According to the docs, it looks like:
1. The `kernelspec` is the only notebook-level metadata field officially defined, so nothing crucial should depend on `language_info` ([here](http://nbformat.readthedocs.io/en/latest/format_description.html#metadata))
2. If `language_info` is defined, its `name` field is required, but nothing is said about the `version` field ([here](http://nbformat.readthedocs.io/en/latest/format_description.html#top-level-structure))

So it looks like it should be safe (and easier) to just drop the field.
I tried with Python 2 and Julia notebooks and it didn't give any problem.

I'll make the PR

**Comment by toobaz** [comment]
Great, thanks for checking.

**Comment by toobaz** [comment]
Closed via #14
