### ISSUE TITLE
Shebang still uses Python 2

### ISSUE THREAD

**Issue by Wrzlprmft** [toobaz/ipynb_output_filter#18]
The shebang (`#!/usr/bin/env python`) still refers to `python`, which at least on Linux generally refers to Python 2 as far as I know. I don’t know whether using `python3` would work in all contexts here, but I had to change this to get things working. At the very least there could be a warning in the instructions.

(Also, the Python 2 hooks can arguably be retired now, as it is officially dead.)

**Comment by toobaz** [comment]
Fixed, thanks!
