### ISSUE TITLE
Reconsider whether to strip out "id" field

### ISSUE THREAD

**Issue by AllanChain** [toobaz/ipynb_output_filter#19]
The commit db50349c0c066382bddb67e3695b329507818092 strips "id" field out.

But GitHub fails to recognize the notebook if the "id" field is `null`.

- Without "id": https://github.com/AllanChain/fastbook-but-jax/blob/157567d/mnist.ipynb
- With "id": https://github.com/AllanChain/fastbook-but-jax/blob/0e1d9b8/mnist.ipynb

Also, if I try to delete the "id" field instead of setting it to `None`, nbformat will automatically re-add the field. So I don't think stripping out the "id" field is a good idea.

Furthermore, the "id" field is required to be a string in the schema:
- https://github.com/jupyter/nbformat/blob/b23aad6e29d8c3909a1b04a7edc9ae541096dc7b/nbformat/v4/nbformat.v4.schema.json#L98-L104
- https://github.com/jupyter/nbformat/blob/b23aad6e29d8c3909a1b04a7edc9ae541096dc7b/nbformat/v4/nbformat.v4.schema.json#L187-L198

**Comment by toobaz** [comment]
Hi, thanks @AllanChain for signaling this.

I'm now reverting the problematic commit, and I'm trying to understand if there is a better way to fix this.

[This answer on stackoverflow](https://stackoverflow.com/a/68037340/2858145) makes me pessimistic: setting the id to a constant value does not work. I will test to better understand what "does not work" means.

An alternative is to assign ids uniquely based on the position of the cell in the notebook, e.g. "cell-1", "cell-2". This means that the ids would always change if a cell is inserted above, but it would still be better than the current state of things, where all ids change for random reasons.

Further suggestions are welcome.

**Comment by toobaz** [comment]
> An alternative is to assign ids uniquely based on the position of the cell in the notebook, e.g. "cell-1", "cell-2"

... or maybe better, some simple hash of the cell content (not output)?

**Comment by AllanChain** [comment]
JupyterLab has done a lot to make the cell id consistent. Maybe stripping out the id field is not very necessary.

Anyway, [here is a simple implementation](https://github.com/doconce/doconce/blob/d129bf6cc5c1e1079c9a1ab273b03bbbd1f9fb5c/lib/doconce/ipynb.py#L765-L777) I found if need to use the hash of the content.

**Comment by toobaz** [comment]
> Maybe stripping out the id field is not very necessary.

I did have annoying and unjustified changes in my diffs, to cells featuring no other changes. But I guess if nobody is complaining, I maybe did something weird. I will test a bit more, thanks.
