### ISSUE TITLE
No module named IPython.nbformat.current

### ISSUE THREAD

**Issue by basnijholt** [toobaz/ipynb_output_filter#2]
I thought I would completely start a new repo where I don't save outputs. 

So I did `git init` and applied the filters, but now I get the following error:

```
  File "/Users/basnijholt/orbitalfield/scripts/ipynb_output_filter.py", line 16, in <module>
    from IPython.nbformat.current import reads, write
ImportError: No module named IPython.nbformat.current
error: external filter ~/orbitalfield/scripts/ipynb_output_filter.py failed 1
```

Any idea?

**Comment by toobaz** [comment]
Maybe you have  ipython notebooks installed only for Python 3 and not Python 2?
(i.e. package `ipython3-notebook` but not `ipython-notebook` under Debian/Ubuntu)

(in any case this issue is not related to git)

**Comment by lzkelley** [comment]
I had the same problem when the script was using the wrong version of python (should be `/opt/local/bin/python` for me, instead of `/usr/bin/python`).  Try doing something like,

python -c "from IPython.nbformat.current import reads, write"

in your command line.

That the script is trying to perform this import suggests that your ipython isn't up-to-date.  What version of ipython are you using?

**Comment by basnijholt** [comment]
I do have the latest IPython version. The trick was to change `clean = ~/orbitalfield/scripts/ipynb_output_filter.py` into `clean = python ~/orbitalfield/scripts/ipynb_output_filter.py` because it picked the defaults OSX Python instead of the `homebrew` version.

Maybe you should change this in the `README`.

One other error that I get with every commit it the following:

``` python
Traceback (most recent call last):
  File "/Users/basnijholt/orbitalfield/scripts/ipynb_output_filter.py", line 55, in <module>
    write(json_in, sys.stdout, version)
  File "/usr/local/lib/python2.7/site-packages/IPython/nbformat/__init__.py", line 161, in write
    fp.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 13103: ordinal not in range(128)
error: external filter python ~/orbitalfield/scripts/ipynb_output_filter.py failed 1
error: external filter python ~/orbitalfield/scripts/ipynb_output_filter.py failed
```

Apparently it doesn't handle long dashes to well.

**Comment by lzkelley** [comment]
This seems like a great fix --- which would solve the same problem I was having.  I think this should be added as a pull-request.

**Comment by toobaz** [comment]
Done, see https://github.com/toobaz/ipynb_output_filter/commit/adef13fd6b875d0701337971eda5db4410994f50 .

@basnijholt , your encoding problem should be solved by the merge I just accepted 5 minutes ago, right?
